---
name: flutix
description: A new Flutter application.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^1.3.0
  cloud_firestore: ^0.13.4+2
  cupertino_icons: ^1.0.0
  email_validator: ^1.0.6
  equatable: ^1.1.1
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.15.5+3
  firebase_core: ^0.4.5
  firebase_storage: ^3.1.5
  flushbar: ^1.10.4
  flutter_bloc: ^3.2.0
  flutter_masked_text: ^0.8.0
  flutter_spinkit: ^4.1.2+1
  flutter_ticket_widget: ^0.0.1
  font_awesome_flutter: ^8.10.0
  google_fonts: ^1.1.1
  http: ^0.12.2
  image_picker: ^0.6.7+12
  intl: ^0.16.1
  provider: ^4.0.4
  qr_flutter: ^3.2.0
  random_string: ^2.0.1
  rflutter_alert: ^1.1.0
  shimmer: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
