import 'package:flutix/models/models.dart';
import 'package:flutix/shared/shared.dart';
import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:intl/intl.dart';
import 'package:flutix/extensions/extensions.dart';
import 'package:rflutter_alert/rflutter_alert.dart';

part 'selectable_box.dart';
part 'movie_card.dart';
part 'rating_bar.dart';
part 'browse_button.dart';
part 'promo_card.dart';
part 'cast_card.dart';
part 'date_card.dart';
part 'amount_card.dart';
part 'history_transaction.dart';
part 'list_genre.dart';
part 'show_image.dart';
